# Generated by Django 4.0.1 on 2022-01-22 14:04

import demo_backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=120)),
                ('points', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=demo_backend.models.upload_path)),
            ],
        ),
    ]
