# Generated by Django 3.2.9 on 2022-01-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotator',
            name='points',
        ),
        migrations.AddField(
            model_name='annotator',
            name='height',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annotator',
            name='width',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annotator',
            name='x',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annotator',
            name='y',
            field=models.TextField(blank=True, null=True),
        ),
    ]
